<?xml-stylesheet type="text/xsl" href="Sample.xsl"?>
<!DOCTYPE root [
	<!ELEMENT id (ratings, namings, id_season, types)>
	<!ATTLIST id id ID #IMPLIED>
	<!ELEMENT ratings EMPTY>
	<!ATTLIST ratings user_rating CDATA #REQUIRED>
	<!ATTLIST ratings year_rating CDATA #REQUIRED>
	<!ELEMENT namings EMPTY>
	<!ATTLIST namings original CDATA #REQUIRED>
	<!ATTLIST namings local CDATA #REQUIRED>
	<!ELEMENT id_season (types)>
	<!ATTLIST id_season id_season ID #IMPLIED>
	<!ELEMENT types EMPTY>
	<!ATTLIST types films CDATA #REQUIRED>
	<!ATTLIST types serials CDATA #REQUIRED>
	<!ATTLIST types anounced CDATA #REQUIRED>
]>
<root>
<id id="A1">
  <ratings user_rating="4.000000000000000e+000" year_rating="r21" />
  <namings original="Rqnbehtaerickek" local="Аватар короля" />
  <id_season id_season="3">
    <types films="602" serials="278" anounced="85" />
  </id_season>
</id>
<!--First comment-->
<id id="A2">
  <ratings user_rating="4.800000000000000e+000" year_rating="r18" />
  <namings original="Ojsiryoktxokbgh" local="Актёры ослеплённого города" />
  <id_season id_season="3">
    <types films="602" serials="278" anounced="85" />
  </id_season>
</id>
<!--Second comment-->
<id id="3">
  <ratings user_rating="4.900000000000000e+000" year_rating="r21" />
  <namings original="Lczkitxcnkgbnfzn" local="Ангельские ритмы!" />
  <id_season id_season="1">
    <types films="490" serials="95" anounced="49" />
  </id_season>
</id>
<id id="5">
  <ratings user_rating="4.900000000000000e+000" year_rating="r18" />
  <namings original="Jnctblpnypfmipba" local="Бездомный бог" />
  <id_season id_season="2">
    <types films="338" serials="222" anounced="56" />
  </id_season>
</id>
<id id="6">
  <ratings user_rating="4.500000000000000e+000" year_rating="r13" />
  <namings original="Fqopnoeiakjmkocnmpw" local="Безумный азарт" />
  <id_season id_season="1">
    <types films="490" serials="95" anounced="49" />
  </id_season>
</id>
<id id="7">
  <ratings user_rating="4.600000000000000e+000" year_rating="r18" />
  <namings original="Vdbssmbbjxguidjru" local="Белый ящик" />
  <id_season id_season="2">
    <types films="338" serials="222" anounced="56" />
  </id_season>
</id>
<id id="8">
  <ratings user_rating="4.200000000000000e+000" year_rating="r13" />
  <namings original="Gncodanoyqqtkbayz" local="Большой магический перевал" />
  <id_season id_season="2">
    <types films="338" serials="222" anounced="56" />
  </id_season>
</id>
<id id="10">
  <ratings user_rating="4.100000000000000e+000" year_rating="r21" />
  <namings original="Dwocsdwupryozmnmcs" local="В воскресенье даже Бог отдыхает" />
  <id_season id_season="3">
    <types films="602" serials="278" anounced="85" />
  </id_season>
</id>
<id id="13">
  <ratings user_rating="4.200000000000000e+000" year_rating="r21" />
  <namings original="Qomazothcwnmkhjrbr" local="Волчица и пряности" />
  <id_season id_season="3">
    <types films="602" serials="278" anounced="85" />
  </id_season>
</id>
<id id="14">
  <ratings user_rating="4.200000000000000e+000" year_rating="r13" />
  <namings original="Mlwezxrvkxxjhoa" local="Восточный Эдем" />
  <id_season id_season="2">
    <types films="338" serials="222" anounced="56" />
  </id_season>
</id>
<id id="15">
  <ratings user_rating="4.800000000000000e+000" year_rating="r13" />
  <namings original="Xgyazsqyohjlhcyljz" local="Врата: Там бьются наши воины" />
  <id_season id_season="1">
    <types films="490" serials="95" anounced="49" />
  </id_season>
</id>
<id id="16">
  <ratings user_rating="3.500000000000000e+000" year_rating="r13" />
  <namings original="Rhsbhhmdcniuswh" local="Габриэль бросает школу" />
  <id_season id_season="1">
    <types films="490" serials="95" anounced="49" />
  </id_season>
</id>
<id id="17">
  <ratings user_rating="4.600000000000000e+000" year_rating="r21" />
  <namings original="Jugsrollwgwghossm" local="Геймеры!" />
  <id_season id_season="2">
    <types films="338" serials="222" anounced="56" />
  </id_season>
</id>
<id id="18">
  <ratings user_rating="3.500000000000000e+000" year_rating="r18" />
  <namings original="Rdljgoejqiwdckgfbu" local="Город в котором меня нет" />
  <id_season id_season="1">
    <types films="490" serials="95" anounced="49" />
  </id_season>
</id>
</root> 